config/routes.rb
Rails.application.routes.draw do

  get 'test/test_page' => 'test#test_page'
  get 'test/result_page' => 'test#result_page'

  root 'welcome#index'
  match 'welcome/index', via: [:get,:post], controller: :welcome, action: :index, as: 'index_page'
  match 'welcome/search_result', via: [:get], controller: :welcome, action: :search_result, as: 'search_result_page'
  match 'welcome/review_request', via: [:post], controller: :welcome, action: :review_request, as: 'review_request'
  match 'welcome/suggest_form', via: [:post], controller: :welcome, action: :suggest_form, as: 'suggest_form'
  match 'welcome/create_request', via: [:post], controller: :welcome, action: :create_request, as: 'create_request'
  match 'welcome/like', via: [:post], controller: :welcome, action: :like
  match 'welcome/detail/:id', via: [:get], controller: :welcome, action: :detail, as:'welcome_detail'
  match 'welcome/post_comment', via: [:post], controller: :welcome, action: :post_comment, as:'new_post_comment'
  match 'welcome/delete_comment', via: [:post], controller: :welcome, action: :delete_comment
  match 'welcome/load_more_comment', via: [:get], controller: :welcome, action: :load_more_comment

  match 'login/login_page', via: [:get], controller: :login, action: :login_page, as: 'login_page'
  match 'login/sign_in', via: [:post], controller: :login, action: :sign_in
  match 'login/logout_page', via: [:get], controller: :login, action: :logout_page, as: 'logout_page'

  match 'suggest/suggest_page', via: [:get], controller: :suggest, action: :suggest_page, as: 'suggest_page'
  match 'suggest/create_suggestion', via: [:post], controller: :suggest, action: :create_suggestion
  match 'suggest/list_book', via: [:post], controller: :suggest, action: :list_book

  match 'manage_book/approve_page', via: [:get], controller: :manage_book, action: :approve_page, as:'approve_page'
  match 'manage_book/managebook_page', via: [:get], controller: :manage_book, action: :managebook_page, as:'managebook_page'
  match 'manage_book/approve/', via: [:post], controller: :manage_book, action: :approve
  match 'manage_book/deny/', via: [:post], controller: :manage_book, action: :deny
  match 'manage_book/unapprove/:id', via: [:get], controller: :manage_book, action: :unapprove
  match 'manage_book/detail_page/:id', via: [:get], controller: :manage_book, action: :detail_page, as:'detail_page'
  match 'manage_book/management_detail_page/:id', via: [:get], controller: :manage_book, action: :management_detail_page, as:'management_detail_page'
  match 'manage_book/update', via: [:post], controller: :manage_book, action: :update
  match 'manage_book/delete/:id', via: [:get], controller: :manage_book, action: :delete
  match 'manage_book/myrequest_page', via: [:get], controller: :manage_book, action: :myrequest_page, as: 'myrequest_page'
  match 'manage_book/filter_myrequest', via: [:get], controller: :manage_book, action: :filter_myrequest

  match 'manage_book/cancel_request/:id', via: [:get], controller: :manage_book, action: :cancel_request
  match 'manage_book/modal_detail', via: [:post], controller: :manage_book, action: :modal_detail

  match 'suggest_list/suggest_list_page', via: [:get], controller: :suggest_list, action: :suggest_list_page, as: 'suggest_list_page'
  match 'suggest_list/detail_suggest_list_page/:id', via: [:get], controller: :suggest_list, action: :detail_suggest_list_page, as: 'detail_suggest_list_page'

end

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title || 'Demo page' %></title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag("#{controller_name}/#{action_name}") if stylesheet_exists? "#{controller_name}/#{action_name}" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta charset="UTF-8">
  <script>$('.dropdown-toggle').dropdown()</script>
</head>

app/views/layouts/application.html.erb
<%= render 'layouts/header' %>

<body>
<nav class="navbar-default main-nav navbar-fixed-top navbar-header">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
      <a id="text-navbar-logo" class="navbar-brand" >Book Management</a>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div>
      <div class="hidden-xs hidden-sm">
        <ul class="nav navbar-nav">
          <% if session[:user].nil? %>
              <li>
                <a id="text-navbar-label" class = "nav-home" href="/welcome/index"><span class="glyphicon glyphicon-home"></span>Home</a>
              </li>
          <% else
               if @role == 0 %>
                  <li>
                    <a id="text-navbar-label" class = "nav-home" href="/welcome/index"><span class="glyphicon glyphicon-home"></span>Home</a>
                  </li>
                  <li>
                    <a id="text-navbar-label" class = "nav-create" href='#' onclick="call_modal('modal_suggestion');"><span class="glyphicon glyphicon-plus"></span>Create</a>
                  </li>
              <% else
                   if @role == 1 %>
                      <li>
                        <a id="text-navbar-label" class = "nav-home" href="/welcome/index"><span class="glyphicon glyphicon-home"></span>Home</a>
                      </li>
                      <li>
                        <a id="text-navbar-label" class = "nav-approval" href="/manage_book/approve_page"><span class="glyphicon glyphicon glyphicon-ok"></span>Approval</a>
                      </li>
                      <li>
                        <a id="text-navbar-label" class = "nav-management" href="/manage_book/managebook_page"><span class="glyphicon glyphicon-edit"></span>Management</a>
                      </li>
                  <% end %>
              <% end %>
          <% end %>
        </ul>
      </div>
      <div class="navbar-right">
        <div class="hidden-xs hidden-sm">
          <%= form_tag '/welcome/search_result', method: :get, class: 'navbar-form' do %>
              <ul class="nav navbar-nav">
                <!--search bar-->
                <li>
                  <div class='form-group hidden-xs'>
                    <%= search_field_tag 'tf_search', nil, class: 'form-control', placeholder: "Enter book's name", autocomplete: 'off' %>
                    <%= submit_tag 'Search', class: 'btn btn-default' %>
                  </div>
                </li>
                <!--end search bar-->
                <% if session[:user].nil? %>
                    <li id="btn_login_logout">
                      <a id="text-navbar" href="/login/login_page" class="navbar-brand">Login</a>
                    </li>
                    <%else if @role == 0 %>
                        <div class="btn-group orange">
                          <button class="btn dropdown-toggle orange" data-toggle="dropdown" >
                            <span class="glyphicon glyphicon-user"></span>
                            <span><%= session[:user] %></span>
                            <span class="caret"></span>
                          </button>
                          <ul class="dropdown-menu dropdown_menu_desktop">
                            <li>
                              <a href="/manage_book/myrequest_page"><span class="glyphicon glyphicon-folder-open"></span>My request</a>
                            </li>
                            <li>
                              <a href="<%=logout_page_path %>"><span class="glyphicon glyphicon-log-out"></span>Logout</a>
                            </li>
                          </ul>
                        </div>
                    <% else %>
                    <div class="btn-group orange">
                      <button class="btn dropdown-toggle orange" data-toggle="dropdown" >
                        <span class="glyphicon glyphicon-user"></span>
                        <span><%= session[:user] %></span>
                        <span class="caret"></span>
                      </button>
                      <ul class="dropdown-menu dropdown_menu_desktop">
                        <li><a href="<%= logout_page_path %>">Logout</a></li>
                      </ul>
                    </div>
                    <% end  %>
                <% end %>
              </ul>
          <% end %>
        </div>

        <div class="btn-group visible-xs visible-sm nav-xs-sm nav_right_mobile">
          <div class="menu_mobile">
            <button class="btn button_menu_mobile dropdown-toggle orange glyphicon glyphicon-align-justify" data-toggle="dropdown" onclick="expand_dropdown_button()">
            </button>
            <ul class="dropdown-menu dropdown_menu_mobile">
              <% if session[:user].nil?  %>
                  <li>
                    <a class = "nav-mobile" href="/welcome/index"><span class="glyphicon glyphicon-home"></span>Home</a>
                  </li>
                  <li id="btn_login_logout">
                    <a class="nav-mobile" href="/login/login_page" ><span class="glyphicon glyphicon-log-in"></span>Login</a>
                  </li>
              <% end %>
              <% if @role == 1  %>
                  <li class="user_name">
                      <span class="glyphicon glyphicon-user"></span>
                      <span><%= session[:user] %></span>
                  </li>
                  <li role="separator" class="divider"></li>
                  <li>
                    <a class = "nav-mobile" href="/welcome/index"><span class="glyphicon glyphicon-home"></span>Home</a>
                  </li>
                  <li>
                    <a class = "nav-mobile" href="/manage_book/approve_page"><span class="glyphicon glyphicon glyphicon-ok"></span>Approval</a>
                  </li>
                  <li>
                    <a href="/manage_book/managebook_page"><span class="glyphicon glyphicon-edit"></span>Management</a>
                  </li>
                  <li>
                    <a href="<%=logout_page_path %>"><span class="glyphicon glyphicon-log-out"></span>Logout</a>
                  </li>
              <% end %>

              <% if @role == 0  %>
                  <li class="user_name">
                    <span class="glyphicon glyphicon-user"></span>
                    <span><%= session[:user] %></span>
                  </li>
                  <li role="separator" class="divider"></li>
                  <li>
                    <a class = "nav-mobile" href="/welcome/index"><span class="glyphicon glyphicon-home"></span>Home</a>
                  </li>
                  <li>
                    <a id="text-navbar-label" class = "nav-create" href='#' onclick="call_modal('modal_suggestion');"><span class="glyphicon glyphicon-plus"></span>Create</a>
                  </li>
                  <li>
                    <a href="/manage_book/myrequest_page"><span class="glyphicon glyphicon-folder-open"></span>My request</a>
                  </li>
                  <li>
                    <a href="<%=logout_page_path %>"><span class="glyphicon glyphicon-log-out"></span>Logout</a>
                  </li>
              <% end  %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div><!-- /.navbar-collapse -->
</nav>



<div class='div-body row'>
  <div class="div_blur" onclick="hide_div_blur()"></div>
  <div class="waiting_div">
    <!--<img src="/assets/images/waiting.gif">-->
  </div>
  <div class="div-content container-fluid col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <%= yield %>
  </div>

</div>
<%= render 'layouts/footer' %>


<!--Begin of modal-->
<div id = "modal_suggestion" class="modal modal_suggestion fade" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Suggest a book</h4>
      </div>
      <div class="modal-body">
        <!--Suggest form-->
        <%= form_tag 'create_suggestion', method: :post, class: 'main_form', id: 'create_request_form' do %>
            <div class="div-suggest">
              <div class='form-group'>
                <label class='form_label'>Name</label>
                <%= text_field_tag 'tf_book_name', nil, class: 'form-control', id: 'id_tf_book_name', autocomplete: 'off' %>
                <label class='error_label label' id='id_label_tf_bookname'></label>
              </div>
              <div class='form-group'>
                <label class='form_label'>Link</label>
                <%= text_field_tag 'tf_book_link', nil, class: 'form-control', id: 'id_tf_book_link', autocomplete: 'off', value: 'http://' %>
                <label class='error_label label' id='id_label_tf_booklink'></label>
              </div>
              <div class='form-group'>
                <label class='form_label'>Link image</label>
                <%= text_field_tag 'tf_link_image', nil, class: 'form-control', id: 'id_tf_link_image', autocomplete: 'off'%>
                <label class='error_label label' id='id_label_linkimage'></label>
              </div>
              <div class='form-group'>
                <label class='form_label'>Price</label>
                <%= text_field_tag 'tf_book_price', nil, class: 'form-control', id: 'id_tf_book_price', type: 'number', step: 'any', autocomplete: 'off' %>
                <label class='error_label label' id='id_label_tf_bookprice'></label>
              </div>
              <div class='form-group'>
                <label class='form_label'>Quantity</label>
                <%= text_field_tag 'tf_book_quantity', nil, class: 'form-control', id: 'id_tf_book_quantity', type: 'number', step: 'any', autocomplete: 'off' %>
                <label class='error_label label' id='id_label_tf_bookquantity'></label>
              </div>
            </div>
            </div> <!--end modal-body-->
            <div class="modal-footer">
              <button class="btn btn-success btn_next" type="button" onclick="check_input_form_modal()">Next</button>
              <button class="btn btn-danger button" type="reset">Reset</button>
              <button class="btn btn-secondary button btn_cancel" type="button" onclick="cancel_request();">Cancel</button>
            </div>
        <% end %>
        </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<!--End of modal-->

</body>